/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:78dc3a5a-7ded-4a60-bf52-346042a01e66",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_joGXWPx0G",
    "aws_user_pools_web_client_id": "5ertbf0cbnhujf20gn4bq3j3br",
    "oauth": {}
};


export default awsmobile;
